"""Addendum §6 — generalisation report across repositories.

Aggregates per-repo outputs + multi-repo dataset stats + LORO into json/csv/md,
including best/worst generalising smell and refactoring types.
"""
from __future__ import annotations

import csv
from pathlib import Path
from typing import Any, Dict, List

from ..config import Config
from ..splits.manager import SplitManager
from ..util import read_json, write_json


def _per_repo_quality(cfg: Config, project_id: str) -> Dict[str, Any]:
    rep = read_json(cfg.data_dir / "outputs" / project_id / "report.json", default={}) or {}
    sugs = read_json(cfg.data_dir / "outputs" / project_id / "suggestions.json", default=[]) or []
    n = len(sugs)
    grounded = sum(1 for s in sugs if not s.get("no_hallucination_checks", {}).get("unsupported_claims"))
    recipes = sum(1 for s in sugs if s.get("openrewrite_recipe_plan", {}).get("recipe_possible"))
    return {
        "project_id": project_id,
        "num_suggestions": n,
        "num_smells": rep.get("num_smells", 0),
        "evidence_grounding_pass_rate": round(grounded / n, 3) if n else 0.0,
        "hallucination_count": rep.get("hallucination_failure_count", 0),
        "json_validity_rate": rep.get("json_validity_rate", 1.0),
        "recipe_draft_count": recipes,
        "recipe_applicability": round(recipes / n, 3) if n else 0.0,
        "topk_recall_vs_history": rep.get("topk_recall_vs_history"),
    }


def _type_generalisation(stats: Dict[str, Any]) -> Dict[str, Any]:
    """Best/worst generalising types by positive-alignment rate across repos."""
    by_ref = stats.get("by_refactoring_type", {})
    by_smell = stats.get("by_smell_type", {})
    best_ref = max(by_ref, key=by_ref.get) if by_ref else None
    worst_ref = min(by_ref, key=by_ref.get) if by_ref else None
    best_smell = max(by_smell, key=by_smell.get) if by_smell else None
    worst_smell = min(by_smell, key=by_smell.get) if by_smell else None
    return {"best_refactoring_type": best_ref, "worst_refactoring_type": worst_ref,
            "best_smell_type": best_smell, "worst_smell_type": worst_smell}


def build_generalisation_report(cfg: Config) -> Dict[str, Any]:
    sm = SplitManager()
    stats = read_json(cfg.data_dir / "reports" / "multi_repo_dataset_stats.json", default={}) or {}
    loro = read_json(cfg.data_dir / "models" / "loro_report.json", default={}) or {}

    # per-repo quality for any repo we have outputs for
    out_dir = cfg.data_dir / "outputs"
    repos_with_outputs = [p.name for p in out_dir.iterdir() if p.is_dir()] if out_dir.exists() else []
    per_repo = [_per_repo_quality(cfg, pid) for pid in sorted(repos_with_outputs)]

    report = {
        "splits": sm.summary(),
        "training_repositories": sm.train,
        "validation_repositories": sm.validation,
        "unseen_test_repositories": sm.unseen,
        "examples_per_repository": stats.get("by_repository", {}),
        "smell_distribution": stats.get("by_smell_type", {}),
        "refactoring_distribution": stats.get("by_refactoring_type", {}),
        "loro_mean_validation_score": loro.get("mean_validation_score"),
        "loro_folds": loro.get("folds", []),
        "per_repository_quality": per_repo,
        "type_generalisation": _type_generalisation(stats),
    }
    write_json(cfg.data_dir / "reports" / "generalisation_report.json", report)
    _write_csv(cfg.data_dir / "reports" / "generalisation_report.csv", per_repo)
    _write_md(Path(__file__).resolve().parent.parent.parent / "docs" / "GENERALISATION_REPORT.md",
              report)
    return report


def _write_csv(path: Path, per_repo: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = ["project_id", "num_smells", "num_suggestions", "evidence_grounding_pass_rate",
              "hallucination_count", "json_validity_rate", "recipe_applicability",
              "topk_recall_vs_history"]
    with open(path, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        for row in per_repo:
            w.writerow(row)


def _write_md(path: Path, report: Dict[str, Any]) -> None:
    tg = report["type_generalisation"]
    lines = [
        "# DSARP Generalisation Report", "",
        "Auto-generated by `dsarp.reporting.generalisation`. Repository-independent features;",
        "Cassandra is unseen-test only.", "",
        "## Splits",
        f"- Train: {', '.join(report['training_repositories']) or '—'}",
        f"- Validation: {', '.join(report['validation_repositories']) or '—'}",
        f"- Unseen test: {', '.join(report['unseen_test_repositories']) or '—'}", "",
        "## Dataset", f"- Examples per repository: {report['examples_per_repository']}",
        f"- Smell distribution: {report['smell_distribution']}",
        f"- Refactoring distribution: {report['refactoring_distribution']}", "",
        "## Leave-one-repository-out",
        f"- Mean validation score: {report.get('loro_mean_validation_score')}", "",
        "## Type generalisation",
        f"- Best/worst refactoring: {tg['best_refactoring_type']} / {tg['worst_refactoring_type']}",
        f"- Best/worst smell: {tg['best_smell_type']} / {tg['worst_smell_type']}", "",
        "## Per-repository quality", "",
        "| repo | smells | suggestions | grounding | hallucinations | recipe_appl | recall |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in report["per_repository_quality"]:
        lines.append(f"| {r['project_id']} | {r['num_smells']} | {r['num_suggestions']} | "
                     f"{r['evidence_grounding_pass_rate']} | {r['hallucination_count']} | "
                     f"{r['recipe_applicability']} | {r.get('topk_recall_vs_history')} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
