"""Run OpenRewrite recipes via Maven to perform the ACTUAL refactoring on real source.

Flow: derive concrete class moves from the cyclic suggestions -> write a `rewrite.yml`
(a ChangeType recipe per class) at the repo root -> `mvn rewrite:run` applies it to the
source. OpenRewrite relocates the class + rewrites every reference and import.

Needs Maven (bundled at tools/apache-maven-*/ or on PATH) + a JDK, and the target repo to
build. `run_recipe` is bounded and returns status + a tail of the Maven log.
"""
from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# rewrite-maven-plugin version (5.x). Overridable via config.
DEFAULT_PLUGIN = "org.openrewrite.maven:rewrite-maven-plugin:5.42.1"
RECIPE_NAME = "com.dsarp.ArchitecturalRefactoring"

# DSARP's own recipe module (tools/dsarp-recipes). Supplies the transformations stock
# rewrite-java exposes only as visitors, plus field-visibility narrowing which it lacks
# entirely. Build with: mvn -f tools/dsarp-recipes/pom.xml install
CUSTOM_RECIPE_GAV = "com.dsarp:dsarp-recipes:1.0.0"
CUSTOM_RECIPES = ("com.dsarp.recipes.ReduceFieldVisibility",
                  "com.dsarp.recipes.ExtractInterfaceForClass")


def custom_recipes_installed() -> bool:
    """True when the DSARP recipe jar is in the local Maven repository."""
    group, artifact, version = CUSTOM_RECIPE_GAV.split(":")
    jar = (Path.home() / ".m2" / "repository" / Path(group.replace(".", "/"))
           / artifact / version / f"{artifact}-{version}.jar")
    return jar.exists()


def build_custom_recipes(timeout: int = 900) -> Dict[str, Any]:
    """`mvn install` the DSARP recipe module so its recipes become referencable."""
    mvn = find_mvn()
    pom = Path(__file__).resolve().parent.parent.parent / "tools" / "dsarp-recipes" / "pom.xml"
    if not mvn:
        return {"ok": False, "status": "maven_not_found"}
    if not pom.exists():
        return {"ok": False, "status": "recipe_module_missing", "pom": str(pom)}
    try:
        proc = subprocess.run([mvn, "-q", "-B", "-ntp", "-f", str(pom), "install"],
                              capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return {"ok": False, "status": "timeout"}
    ok = proc.returncode == 0 and custom_recipes_installed()
    return {"ok": ok, "status": "installed" if ok else "build_failed",
            "gav": CUSTOM_RECIPE_GAV, "recipes": list(CUSTOM_RECIPES),
            "tail": ((proc.stdout or "") + (proc.stderr or ""))[-1500:]}


def find_mvn() -> Optional[str]:
    """mvn on PATH, else the bundled tools/apache-maven-*/bin/mvn(.cmd)."""
    if shutil.which("mvn"):
        return "mvn"
    tools = Path(__file__).resolve().parent.parent.parent / "tools"
    for pat in ("apache-maven-*/bin/mvn.cmd", "apache-maven-*/bin/mvn"):
        cands = sorted(tools.glob(pat))
        if cands:
            return str(cands[-1].resolve())
    return None


def write_change_type_recipe(repo_path: Path, moves: List[Tuple[str, str]],
                             recipe_name: str = RECIPE_NAME) -> Path:
    """Write rewrite.yml at the repo root: one ChangeType per (oldFQN -> newFQN) move."""
    lines = ["---", "type: specs.openrewrite.org/v1beta/recipe",
             f"name: {recipe_name}",
             "displayName: DSARP architectural refactoring (relocate classes to break smells)",
             "description: Auto-generated by DSARP to mitigate detected architectural smells.",
             "recipeList:"]
    for old, new in moves:
        lines += ["  - org.openrewrite.java.ChangeType:",
                  f"      oldFullyQualifiedTypeName: {old}",
                  f"      newFullyQualifiedTypeName: {new}",
                  "      ignoreDefinition: false"]
    path = Path(repo_path) / "rewrite.yml"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_change_package_recipe(repo_path: Path, merges: List[Tuple[str, str]],
                                recipe_name: str = RECIPE_NAME) -> Path:
    """Write rewrite.yml using ChangePackage: relocate ENTIRE packages (oldPkg -> newPkg).

    Preferred over per-class ChangeType for breaking package cycles. Moving only *some*
    classes out of a package breaks their implicit same-package references (the moved file
    loses access to the siblings it never had to import), so the result does not compile.
    Moving the whole package keeps every intra-package reference intact AND removes the
    package that closed the cycle.
    """
    lines = ["---", "type: specs.openrewrite.org/v1beta/recipe",
             f"name: {recipe_name}",
             "displayName: DSARP architectural refactoring (merge packages to break cycles)",
             "description: Auto-generated by DSARP to mitigate detected architectural smells.",
             "recipeList:"]
    for old, new in merges:
        lines += ["  - org.openrewrite.java.ChangePackage:",
                  f"      oldPackageName: {old}",
                  f"      newPackageName: {new}",
                  "      recursive: false"]
    path = Path(repo_path) / "rewrite.yml"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_composite_recipe(repo_path: Path, entries: List[Any],
                           recipe_name: str = RECIPE_NAME) -> Path:
    """Write rewrite.yml from a list of RecipeEntry objects covering ALL smell types.

    Entries come from dsarp.refactoring.strategies, so one run can relocate packages for a
    cyclic smell, split a God Component, consolidate scattered functionality and delete dead
    abstractions in a single OpenRewrite pass.
    """
    lines = ["---", "type: specs.openrewrite.org/v1beta/recipe",
             f"name: {recipe_name}",
             "displayName: DSARP architectural refactoring (all smell types)",
             "description: Auto-generated by DSARP from tool-detected architectural smells.",
             "recipeList:"]
    for e in entries:
        lines.extend(e.to_yaml_lines())
    path = Path(repo_path) / "rewrite.yml"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def run_recipe(repo_path: Path, recipe_name: str = RECIPE_NAME, dry_run: bool = False,
               plugin: str = DEFAULT_PLUGIN, timeout: int = 2400,
               log_path: Optional[Path] = None) -> Dict[str, Any]:
    """Run the OpenRewrite recipe already written to <repo>/rewrite.yml."""
    mvn = find_mvn()
    if not mvn:
        return {"ok": False, "status": "maven_not_found",
                "note": "Maven not found (PATH or tools/apache-maven-*)."}
    pom = Path(repo_path) / "pom.xml"
    if not pom.exists():
        return {"ok": False, "status": "no_pom",
                "note": "OpenRewrite run needs a Maven pom.xml in the repo."}
    goal = "dryRun" if dry_run else "run"
    # Skip build-audit/quality plugins that would otherwise fail the build before OpenRewrite
    # runs (e.g. apache-rat rejecting our generated rewrite.yml for a missing license header).
    skips = ["-Drat.skip=true", "-Dcheckstyle.skip=true", "-Denforcer.skip=true",
             "-Dmaven.test.skip=true", "-Dspotless.check.skip=true", "-Dspotbugs.skip=true",
             "-Dpmd.skip=true", "-Danimal.sniffer.skip=true", "-Dlicense.skip=true",
             "-Djacoco.skip=true", "-Dmaven.javadoc.skip=true"]
    config = (Path(repo_path) / "rewrite.yml").resolve()
    cmd = [mvn, "-B", "-ntp", "-f", str(pom), f"{plugin}:{goal}",
           f"-Drewrite.activeRecipes={recipe_name}",
           f"-Drewrite.configLocation={config}",
           "-Drewrite.exportDatatables=false", *skips]
    # Put DSARP's custom recipes (field visibility, extract interface) on the plugin's
    # classpath so rewrite.yml can name them alongside the stock ones.
    if custom_recipes_installed():
        cmd.append(f"-Drewrite.recipeArtifactCoordinates={CUSTOM_RECIPE_GAV}")
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return {"ok": False, "status": "timeout", "note": f"exceeded {timeout}s"}
    out = (proc.stdout or "") + "\n" + (proc.stderr or "")
    if log_path:
        Path(log_path).parent.mkdir(parents=True, exist_ok=True)
        Path(log_path).write_text(out, encoding="utf-8")
    ok = proc.returncode == 0
    changed = ("Changes have been made" in out) or ("Please review and commit" in out)
    files = sorted(set(re.findall(r"Changes have been made to\s+(.+?)\s+by:", out)))
    return {"ok": ok, "status": ("changed" if changed else "clean" if ok else "failed"),
            "returncode": proc.returncode, "changed_files": files[:50],
            "recipe": recipe_name, "goal": goal, "tail": out[-2500:], "mvn": mvn}
